#pragma config(Motor,  port2,           FLM,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FRM,           tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.h";

task main()
{
	while(true){
		readController();
		FLMspeed = (rJoyY + rJoyX);
		FRMspeed = (rJoyY - rJoyX);

		setMotorsToRespectiveSpeeds();
	}


}
