#pragma config(Motor,  port2,           FLM,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FRM,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           ClawUpDown,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ClawOpenClose, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.h";

task main()
{
	while(true){
		readController();
		FLMspeed = (rJoyY + rJoyX);
		FRMspeed = (rJoyY - rJoyX);
		clawUDSpeed = (lJoyY);

		if(B5U == 1 && Btn5D == 0){
			clawOCSpeed == 127;
		}
		else if(B5U == 0 && B5D == 1){
			clawOCSpeed == -127;
		}
		else{
			clawOCSpeed == 0;
		}

		setMotorsToRespectiveSpeeds();
	}


}
