#pragma config(Motor,  port2,           FLM,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FRM,           tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ClawUpDown,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ClawOpenClose, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           ScoopUD,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BaseServoL,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           BaseServoR,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "library.h";

task main()
{
	while(true){
		readController();
		FLMspeed = (rJoyY + rJoyX);
		FRMspeed = (rJoyY - rJoyX);
		clawUDSpeed = (lJoyY);

		if(B6U == 1 && B5U == 0){
			clawOCSpeed = 127;
		}
		else if(B6U == 0 && B5U == 1){
			clawOCSpeed = -127;
		}
		else{
			clawOCSpeed = 0;
		}

		if(B6D == 1 && B5D == 0){
			scoopUDSpeed = 127;
		}
		else if(B6D == 0 && B5D == 1){
			scoopUDSpeed = -127;
		}
		else{
			scoopUDSpeed = 0;
		}
		BaseServoLSpeed = lJoyX;
		BaseServoRSpeed= lJoyX;

		setMotorsToRespectiveSpeeds();
	}
}
